apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-java
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
        - name: java
          image: vishnuallampalli/backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: backend-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
