apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: react
          image: vishnuallampalli/forntend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: frontend-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
